# For more about this config: https://docs.netlify.com/configure-builds/file-based-configuration

# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  base = "app/frontend"
  command = "npm run build"
  publish = "dist"

  # Sets a custom directory for Netlify edge functions.
  edge_functions = "app/backend"

[dev]
  command = "npm run dev"

# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
function = "get-data"
path = "/get-data"
